services:
  web:
    image: ghcr.io/theo-maes/solene_php/web:latest
    ports:
      - "80:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mots_meles
      MYSQL_USER: solene
      MYSQL_PASSWORD: solene
    volumes:
      - ./base:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
