services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mots_meles
      MYSQL_USER: solene
      MYSQL_PASSWORD: solene
    ports:
      - 3306:3306
